name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - '**gradle-wrapper.jar'
  push:
    paths:
      - '**gradle-wrapper.jar'

jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
